name: CI

on:
  #
  # Runs tests against the microservice on push to the main branch of this code repository.
  #
  push: 
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@latest

    # 
    # Installs Node.js for use in the workflow.
    #
    - uses: actions/setup-node@latest
      with:
        node-version: 18.x
        cache: 'npm'

    - run: npm ci
    - run: npm test
